# Generated by Django 3.2.9 on 2021-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('trace_msg', models.TextField(verbose_name='异常信息')),
                ('api', models.IntegerField(verbose_name='api-id')),
                ('sys', models.IntegerField(verbose_name='appid')),
            ],
        ),
    ]
