# Generated by Django 3.2.9 on 2021-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRec',
            fields=[
                ('request_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='请求时间')),
                ('request_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='请求ID')),
                ('request_sys', models.CharField(max_length=255, verbose_name='请求来源系统')),
                ('response_sys', models.CharField(max_length=255, verbose_name='请求目标系统')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_message', models.TextField(verbose_name='请求消息')),
                ('response_message', models.TextField(verbose_name='响应消息')),
                ('api', models.IntegerField(verbose_name='请求的api')),
            ],
        ),
    ]
