# Generated by Django 3.2.9 on 2021-12-09 14:25

import apigw.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestrec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrec',
            name='request_time',
            field=apigw.models.fields.CustomDateTimeField(auto_created=True, auto_now=True, verbose_name='请求时间'),
        ),
    ]
