# Generated by Django 3.2.9 on 2021-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSchema',
            fields=[
                ('api_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='API-ID')),
                ('origin_url', models.CharField(max_length=255, verbose_name='原始url')),
                ('apigw_url', models.CharField(max_length=255, verbose_name='在apigw的url')),
                ('from_sys', models.IntegerField(verbose_name='所属应用')),
                ('name', models.CharField(max_length=128, verbose_name='api名')),
            ],
            options={
                'verbose_name': '网关路由表',
                'unique_together': {('from_sys', 'apigw_url')},
            },
        ),
    ]
